services:
  - type: web
    name: house-price-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=10000 --server.address=0.0.0.0"
